"""Music-theory primitives: pitch/key normalization, chord vocabulary, voice leading."""

from .chords import (
    APPLIED_TARGETS,
    QUALITY_TEMPLATES,
    SEVENTH_QUALITIES,
    TRIAD_QUALITIES,
    ChordLabel,
    analyze_chord,
    build_vocabulary,
    chord_pitch_classes,
    diatonic_collection,
    infer_applied_target,
    make_chord,
    numeral_stem,
)
from .pitch import (
    HARMONIC_MINOR,
    MAJOR_SCALE,
    NATURAL_MINOR,
    NORMALIZED_TONIC,
    Key,
    denormalize_pitches,
    detect_key,
    interval_class,
    is_perfect_fifth,
    is_perfect_octave,
    motion_type,
    normalization_shift,
    normalize_pitches,
    pc,
)
from .voicing import (
    ALTO,
    BASS,
    PREFERRED_RANGES,
    SOPRANO,
    TENOR,
    VOICE_NAMES,
    VOICE_RANGES,
    Defect,
    VoicedTexture,
    analyze_texture,
    count_chord_changes,
    dominant_target,
    find_direct_perfects,
    find_doubled_leading_tone,
    find_overlaps,
    find_parallels,
    find_range_violations,
    find_spacing_errors,
    find_unresolved_leading_tones,
    find_unresolved_sevenths,
    find_voice_crossings,
    melodic_defect,
    texture_from_voices,
)

__all__ = [name for name in dir() if not name.startswith("_")]
