"""Structural cadence tables, measured from the Bach training split.

GENERATED by `python -m ml.training.calibrate_cadences` — do not edit by hand.

A chord class counts as a plausible ending if it accounts for at least
1% of piece endings (0.1% of phrase endings) in that mode.
Split by mode because closing on a root-position V is a Phrygian half cadence
that Bach writes in 12.8% of minor-key chorales
and only 3.8% of major-key ones.

Calibration: these tables accept 98.9% of Bach's own endings, and
99.2% of his chorales reach a tonic-rooted chord within the first
12 beats. Both numbers are the floor every engine is read against.
"""


PLAUSIBLE_FINAL_CHORDS = {
    'major': frozenset({(0, 'maj'), (5, 'maj'), (7, 'maj'), (9, 'maj'), (9, 'min')}),
    'minor': frozenset({(0, 'maj'), (0, 'min'), (3, 'maj'), (7, 'maj')}),
}

PLAUSIBLE_PHRASE_CHORDS = {
    'major': frozenset({(0, 'dom7'), (0, 'maj'), (2, 'maj'), (2, 'min'), (4, 'dom7'), (4, 'maj'), (4, 'min'), (5, 'maj'), (7, 'dom7'), (7, 'maj'), (7, 'min'), (9, 'maj'), (9, 'min'), (10, 'maj'), (11, 'dim')}),
    'minor': frozenset({(0, 'maj'), (0, 'min'), (2, 'maj'), (3, 'maj'), (5, 'maj'), (5, 'min'), (7, 'dom7'), (7, 'maj'), (7, 'min'), (8, 'maj'), (10, 'maj'), (11, 'maj')}),
}

#: Beats within which a tonic-rooted chord must appear for the key to count
#: as established. Bach reaches one this early in ~100% of chorales.
KEY_ESTABLISHMENT_BEATS = 12
