"""Cadential priors for melody-only key detection, measured from the training split.

GENERATED by `python -m ml.training.calibrate_key` — do not edit by hand.

Log-probability of the soprano's final and first note landing on each scale
degree, given the mode. Used to break the dominant ambiguity that pitch-class
duration alone cannot resolve: a D minor melody and an A minor melody have
similar pitch-class profiles, and the thing that distinguishes them is where the
tune comes to rest.
"""


FINAL_DEGREE_LOGP = {
    'major': (-0.1809, -5.6058, -5.6058, -5.6058, -3.6599, -3.6599, -5.6058, -3.2079, -5.6058, -3.0409, -5.6058, -5.6058),
    'minor': (-0.2477, -5.6276, -4.5290, -3.6817, -4.5290, -4.5290, -4.5290, -2.0723, -5.6276, -5.6276, -5.6276, -4.5290),
}

FIRST_DEGREE_LOGP = {
    'major': (-0.7616, -5.6058, -5.6058, -5.6058, -1.4314, -3.6599, -5.6058, -1.5283, -5.6058, -3.6599, -5.6058, -5.6058),
    'minor': (-0.9002, -5.6276, -4.0182, -2.7944, -5.6276, -3.6817, -5.6276, -0.7993, -5.6276, -5.6276, -4.0182, -5.6276),
}
