"""Calibrate the rule engine's chord priors against the training corpus.

The functional grammar in `ml/engines/rules.py` — what resolves to what, how a
cadential six-four behaves, which chords tonicize which degrees — stays
hand-written; that grammar is what makes it a *rules* engine, and it is the
thing v1's rule engine had and its network did not.

What is not worth guessing is how *often* Bach reaches for each chord. Hand-set
priors put V7 at 19% of all chords where Bach uses it 2%, which is not a
judgement call, it is just a wrong number. So the unigram priors are estimated
from the training split and written out as a table.

This deliberately makes the baseline harder to beat. A learned engine that only
matches a rule engine with guessed priors has not demonstrated anything.

    python -m ml.training.calibrate_rules
"""

from __future__ import annotations

import math
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ml.data.corpus import load_chorales, split_chorales  # noqa: E402
from ml.eval.metrics import beat_chords  # noqa: E402

OUTPUT = Path(__file__).resolve().parents[1] / "engines" / "_rule_priors.py"

#: Log-frequency is squashed toward zero so a rare-but-real chord stays
#: reachable; the search should be biased, not deterministic.
SCALE = 0.65
FLOOR = -2.0


def collect(chorales) -> dict[str, Counter]:
    counts = {"major": Counter(), "minor": Counter()}
    inversions = {"major": Counter(), "minor": Counter()}
    for chorale in chorales:
        mode = chorale.key.mode
        for chord in beat_chords(chorale.voices, chorale.key):
            if chord is None:
                continue
            counts[mode][(chord.relative_root, chord.quality)] += 1
            inversions[mode][chord.inversion] += 1
    return counts, inversions


def to_priors(counter: Counter, *, reference: tuple[int, str]) -> dict[tuple[int, str], float]:
    total = sum(counter.values()) or 1
    reference_p = (counter.get(reference, 1)) / total
    out: dict[tuple[int, str], float] = {}
    for key, count in counter.items():
        if count < 3:
            continue
        prior = SCALE * math.log((count / total) / reference_p) + 1.0
        out[key] = round(max(FLOOR, prior), 3)
    return dict(sorted(out.items(), key=lambda item: -item[1]))


def render(name: str, table: dict) -> str:
    lines = [f"{name} = {{"]
    for (root, quality), value in table.items():
        lines.append(f"    ({root}, {quality!r}): {value},")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    chorales = load_chorales()
    train, _, _ = split_chorales(chorales)
    counts, inversions = collect(train)

    major = to_priors(counts["major"], reference=(0, "maj"))
    minor = to_priors(counts["minor"], reference=(0, "min"))

    inversion_priors = {}
    for mode in ("major", "minor"):
        total = sum(inversions[mode].values()) or 1
        base = inversions[mode].get(0, 1) / total
        for inversion, count in sorted(inversions[mode].items()):
            value = SCALE * math.log(max(count, 1) / total / base)
            inversion_priors.setdefault(inversion, []).append(value)
    merged_inversions = {k: round(sum(v) / len(v), 3) for k, v in inversion_priors.items()}

    header = '''"""Chord priors estimated from the Bach training split.

GENERATED by `python -m ml.training.calibrate_rules` — do not edit by hand.

Values are log-frequency relative to the tonic triad, squashed by 0.65 and
floored, so the rule engine is biased toward what Bach actually writes without
becoming unable to reach a rare chord the melody demands. Only the *frequency*
of each chord is learned here; the functional grammar that decides what may
follow what stays hand-written in rules.py.
"""

'''
    body = "\n".join([
        header,
        render("MAJOR_PRIOR", major),
        "",
        render("MINOR_PRIOR", minor),
        "",
        f"INVERSION_PRIOR = {merged_inversions!r}",
        "",
    ])
    OUTPUT.write_text(body)

    print(f"train pieces: {len(train)}")
    print(f"major chord classes kept: {len(major)}   minor: {len(minor)}")
    print(f"inversion priors: {merged_inversions}")
    print("top major:", list(major.items())[:8])
    print("top minor:", list(minor.items())[:8])
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
