"""Calibrate the cadential evidence used by melody-only key detection.

Krumhansl-Schmuckler weighs pitch-class *durations* and nothing else, and its
best-known failure is confusing a key with its dominant. Measured on this corpus
that failure is 55% of all key-detection errors: 31 of 67 are a minor-key piece
read a fifth too high, plus 6 more in major. A D minor melody dwells on D, F and
A, and A minor's profile rewards exactly those as its own tonic, fourth and
sixth.

The evidence that separates them is cadential and KS ignores it: the soprano's
final note is the tonic 83.7% of the time and the dominant only 8.7%. The old
implementation did use the final note, but as an ad-hoc +0.08 nudge to a
correlation — far too weak to overturn a profile difference, and on a scale that
had no principled relationship to it.

This measures the actual distributions from the training split so the detector
can combine them as log-probabilities instead of guessing a bonus.

    python -m ml.training.calibrate_key
"""

from __future__ import annotations

import math
import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ml.data.corpus import REST, load_chorales, split_chorales  # noqa: E402

OUTPUT = Path(__file__).resolve().parents[1] / "theory" / "_key_priors.py"

#: Add-alpha smoothing. A degree never seen as a final note must stay possible;
#: the point is to bias the search, not to make an answer unreachable.
SMOOTHING = 0.5


def collect(chorales) -> tuple[dict, dict]:
    final = {"major": Counter(), "minor": Counter()}
    first = {"major": Counter(), "minor": Counter()}
    for chorale in chorales:
        soprano = [p for p in chorale.voices[0] if p != REST]
        if not soprano:
            continue
        mode = chorale.key.mode
        final[mode][chorale.key.to_relative(soprano[-1] % 12)] += 1
        first[mode][chorale.key.to_relative(soprano[0] % 12)] += 1
    return final, first


def log_probabilities(counter: Counter) -> list[float]:
    total = sum(counter.values()) + SMOOTHING * 12
    return [round(math.log((counter.get(degree, 0) + SMOOTHING) / total), 4) for degree in range(12)]


def render(name: str, table: dict[str, Counter]) -> str:
    lines = [f"{name} = {{"]
    for mode in ("major", "minor"):
        values = ", ".join(f"{v:.4f}" for v in log_probabilities(table[mode]))
        lines.append(f"    {mode!r}: ({values}),")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    chorales = load_chorales()
    train, _, _ = split_chorales(chorales)
    final, first = collect(train)

    header = '''"""Cadential priors for melody-only key detection, measured from the training split.

GENERATED by `python -m ml.training.calibrate_key` — do not edit by hand.

Log-probability of the soprano's final and first note landing on each scale
degree, given the mode. Used to break the dominant ambiguity that pitch-class
duration alone cannot resolve: a D minor melody and an A minor melody have
similar pitch-class profiles, and the thing that distinguishes them is where the
tune comes to rest.
"""

'''
    body = "\n".join([
        header,
        render("FINAL_DEGREE_LOGP", final),
        "",
        render("FIRST_DEGREE_LOGP", first),
        "",
    ])
    OUTPUT.write_text(body)

    for label, table in (("final", final), ("first", first)):
        for mode in ("major", "minor"):
            total = sum(table[mode].values()) or 1
            top = table[mode].most_common(3)
            summary = ", ".join(f"degree {d}: {100 * c / total:.0f}%" for d, c in top)
            print(f"{label:5s} {mode:5s} (n={total}): {summary}")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
