"""Calibrate the structural-cadence tables from the training corpus.

Structural rules are the easiest place to be confidently wrong. Written from
theory, "a piece must end on the tonic" flags 15% of Bach as catastrophically
broken — because ~8% of his chorales close on a root-position V, a Phrygian half
cadence, and that rate triples in minor keys. Checked against the corpus, only 1
of those 22 pieces has a mistaken key label. Bach is not making a mistake; the
rule was.

So the plausible endings are measured, not asserted, and split by mode because
that is where the difference actually lives. The oracle must score near zero on
anything this file produces: if a structural detector fires on Bach, the detector
is wrong.

    python -m ml.training.calibrate_cadences
"""

from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from ml.data.corpus import STEPS_PER_QUARTER, load_chorales, split_chorales  # noqa: E402
from ml.eval.metrics import beat_chords  # noqa: E402

OUTPUT = Path(__file__).resolve().parents[1] / "theory" / "_cadence_priors.py"

#: An ending must account for at least this share of the corpus's pieces in that
#: mode to count as plausible. Set so Bach scores ~1%, not 0%: a rule tuned until
#: the oracle is exactly zero has been fitted to the oracle rather than
#: calibrated against it, and would have no headroom for real music.
FINAL_THRESHOLD = 0.01
#: Phrase endings are far more varied than piece endings, so the bar is lower.
#: Swept against the oracle: 0.4% flags 4.35% of Bach's chorales, 0.1% flags
#: 1.63%, and below 0.1% nothing further changes. A structural tier is supposed
#: to mean "wrong", not "unusual", so the knee is the right place to sit.
PHRASE_THRESHOLD = 0.001


def collect(chorales):
    finals = {"major": Counter(), "minor": Counter()}
    phrase = {"major": Counter(), "minor": Counter()}
    tonic_delay = Counter()

    for chorale in chorales:
        chords = beat_chords(chorale.voices, chorale.key)
        real = [(index, chord) for index, chord in enumerate(chords) if chord is not None]
        if not real:
            continue
        mode = chorale.key.mode
        finals[mode][(real[-1][1].relative_root, real[-1][1].quality)] += 1

        for index, chord in real:
            if chord.relative_root == 0:
                tonic_delay[index] += 1
                break
        else:
            tonic_delay[-1] += 1

        for index, chord in real:
            step = index * STEPS_PER_QUARTER
            if step >= len(chorale.fermatas) or not chorale.fermatas[step]:
                continue
            following = step + STEPS_PER_QUARTER
            if following < len(chorale.fermatas) and chorale.fermatas[following]:
                continue
            phrase[mode][(chord.relative_root, chord.quality)] += 1
    return finals, phrase, tonic_delay


def keep(counter: Counter, threshold: float) -> set:
    total = sum(counter.values()) or 1
    return {key for key, count in counter.items() if count / total >= threshold}


def render(name: str, table: dict[str, set]) -> str:
    lines = [f"{name} = {{"]
    for mode in ("major", "minor"):
        entries = ", ".join(repr(entry) for entry in sorted(table[mode]))
        lines.append(f"    {mode!r}: frozenset({{{entries}}}),")
    lines.append("}")
    return "\n".join(lines)


def main() -> int:
    chorales = load_chorales()
    train, _, _ = split_chorales(chorales)
    finals, phrase, tonic_delay = collect(train)

    plausible_finals = {mode: keep(finals[mode], FINAL_THRESHOLD) for mode in finals}
    plausible_phrase = {mode: keep(phrase[mode], PHRASE_THRESHOLD) for mode in phrase}

    total_pieces = sum(sum(c.values()) for c in finals.values())
    covered = sum(
        count for mode in finals for key, count in finals[mode].items()
        if key in plausible_finals[mode]
    )
    delay_total = sum(tonic_delay.values()) or 1
    within = sum(v for k, v in tonic_delay.items() if 0 <= k <= 12)

    header = f'''"""Structural cadence tables, measured from the Bach training split.

GENERATED by `python -m ml.training.calibrate_cadences` — do not edit by hand.

A chord class counts as a plausible ending if it accounts for at least
{FINAL_THRESHOLD:.0%} of piece endings ({PHRASE_THRESHOLD:.1%} of phrase endings) in that mode.
Split by mode because closing on a root-position V is a Phrygian half cadence
that Bach writes in {100 * finals["minor"][(7, "maj")] / max(1, sum(finals["minor"].values())):.1f}% of minor-key chorales
and only {100 * finals["major"][(7, "maj")] / max(1, sum(finals["major"].values())):.1f}% of major-key ones.

Calibration: these tables accept {100 * covered / max(1, total_pieces):.1f}% of Bach's own endings, and
{100 * within / delay_total:.1f}% of his chorales reach a tonic-rooted chord within the first
12 beats. Both numbers are the floor every engine is read against.
"""

'''
    body = "\n".join([
        header,
        render("PLAUSIBLE_FINAL_CHORDS", plausible_finals),
        "",
        render("PLAUSIBLE_PHRASE_CHORDS", plausible_phrase),
        "",
        "#: Beats within which a tonic-rooted chord must appear for the key to count",
        "#: as established. Bach reaches one this early in ~100% of chorales.",
        "KEY_ESTABLISHMENT_BEATS = 12",
        "",
    ])
    OUTPUT.write_text(body)

    print(f"train pieces: {total_pieces}")
    for mode in ("major", "minor"):
        print(f"  {mode}: {len(plausible_finals[mode])} plausible finals, "
              f"{len(plausible_phrase[mode])} plausible phrase endings")
    print(f"finals covered: {100 * covered / max(1, total_pieces):.1f}%")
    print(f"tonic within 12 beats: {100 * within / delay_total:.1f}%")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
